import { NextResponse } from "next/server";
import { siteUrl } from "@/lib/seo";
import { isAieoEnabled } from "@/config/features";

export function GET() {
    const primarySitemap = `${siteUrl}/sitemap.xml`;
    const lines = [
        "# robots.txt generated by Ibrahim Ben Abdallah",
        "User-agent: *",
        "Allow: /",
    ];

    if (isAieoEnabled) {
        lines.push(
            "# AI crawlers: visit /ai-brief for the canonical knowledge brief."
        );
    }

    lines.push(`Sitemap: ${primarySitemap}`);

    return new NextResponse(lines.join("\n"), {
        status: 200,
        headers: {
            "Content-Type": "text/plain; charset=utf-8",
            "Cache-Control":
                "public, max-age=3600, stale-while-revalidate=86400",
        },
    });
}
